# Generated by Django 6.0.4 on 2026-04-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slag',
            field=models.SlugField(blank=True),
        ),
    ]
