# Generated by Django 6.0.4 on 2026-04-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_user_slag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slag',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
