# Generated by Django 6.0.4 on 2026-04-29 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_user_slag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='slag',
            new_name='slug',
        ),
    ]
